/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-1-g7357994-dirty+7357994f8ca5cb5d1a8699245e834022c176cb0d

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   canboss_master.h; canboss_master.c
        Project File: canboss_master.eds
        File Version: 1

        Created:      07/14/2026 12:00:00
        Created By:   Protronic
        Modified:     07/14/2026 12:00:00
        Modified By:  Protronic

    Device Info:
        Vendor Name:  Protronic
        Vendor ID:    0
        Product Name: CANboss-Master
        Product ID:   0

        Description:  Demo-Netzwerk: CANboss Master/Monitor - empfaengt alle PDOs der Demo-Knoten, Node 127
*******************************************************************************/

#ifndef canboss_master_H
#define canboss_master_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define canboss_master_CNT_NMT 1
#define canboss_master_CNT_EM 1
#define canboss_master_CNT_SYNC 1
#define canboss_master_CNT_SYNC_PROD 1
#define canboss_master_CNT_STORAGE 1
#define canboss_master_CNT_TIME 1
#define canboss_master_CNT_EM_PROD 1
#define canboss_master_CNT_HB_CONS 1
#define canboss_master_CNT_HB_PROD 1
#define canboss_master_CNT_SDO_SRV 1
#define canboss_master_CNT_SDO_CLI 1
#define canboss_master_CNT_RPDO 7
#define canboss_master_CNT_TPDO 2


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define canboss_master_CNT_ARR_1003 16
#define canboss_master_CNT_ARR_1010 4
#define canboss_master_CNT_ARR_1011 4
#define canboss_master_CNT_ARR_1016 8
#define canboss_master_CNT_ARR_2110 4
#define canboss_master_CNT_ARR_2112 4


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[canboss_master_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1404_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1405_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1406_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1604_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1605_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1606_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
    } x1A01_TPDOMappingParameter;
} canboss_master_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    char x1008_manufacturerDeviceName[15];
    char x1009_manufacturerHardwareVersion[4];
    char x100A_manufacturerSoftwareVersion[4];
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[canboss_master_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[canboss_master_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    uint8_t x2110_IO_AnalogeEingaenge_sub0;
    int16_t x2110_IO_AnalogeEingaenge[canboss_master_CNT_ARR_2110];
    float32_t x2111_IO_Temperatur;
    uint8_t x2112_IO_DigitaleEingaenge_sub0;
    bool_t x2112_IO_DigitaleEingaenge[canboss_master_CNT_ARR_2112];
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t statusword;
        int16_t drehzahlRampe;
        int16_t drehzahlIst;
    } x2120_antriebStatus;
    struct {
        uint8_t highestSub_indexSupported;
        int32_t motorstromMA;
        float32_t temperaturEndstufe;
    } x2121_antriebMesswerte;
    struct {
        uint8_t highestSub_indexSupported;
        float32_t temperatur;
        float32_t relativeFeuchte;
    } x2130_sensorKlima;
    struct {
        uint8_t highestSub_indexSupported;
        float32_t luftdruckHPa;
        uint32_t messzaehler;
    } x2131_sensorUmgebung;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t alarmstatus;
        bool_t alarmAktiv;
    } x2132_sensorAlarm;
    struct {
        uint8_t highestSub_indexSupported;
        bool_t ausgang1;
        bool_t ausgang2;
        bool_t ausgang3;
        bool_t ausgang4;
        int16_t sollwert;
    } x2210_IO_Kommando;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t controlword;
        int16_t drehzahlSollwert;
        bool_t bremseAktiv;
    } x2220_antriebKommando;
} canboss_master_RAM_t;

#ifndef canboss_master_ATTR_PERSIST_COMM
#define canboss_master_ATTR_PERSIST_COMM
#endif
extern canboss_master_ATTR_PERSIST_COMM canboss_master_PERSIST_COMM_t canboss_master_PERSIST_COMM;

#ifndef canboss_master_ATTR_RAM
#define canboss_master_ATTR_RAM
#endif
extern canboss_master_ATTR_RAM canboss_master_RAM_t canboss_master_RAM;

#ifndef canboss_master_ATTR_OD
#define canboss_master_ATTR_OD
#endif
extern canboss_master_ATTR_OD OD_t *canboss_master;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define canboss_master_ENTRY_H1000 &canboss_master->list[0]
#define canboss_master_ENTRY_H1001 &canboss_master->list[1]
#define canboss_master_ENTRY_H1003 &canboss_master->list[2]
#define canboss_master_ENTRY_H1005 &canboss_master->list[3]
#define canboss_master_ENTRY_H1006 &canboss_master->list[4]
#define canboss_master_ENTRY_H1007 &canboss_master->list[5]
#define canboss_master_ENTRY_H1008 &canboss_master->list[6]
#define canboss_master_ENTRY_H1009 &canboss_master->list[7]
#define canboss_master_ENTRY_H100A &canboss_master->list[8]
#define canboss_master_ENTRY_H1010 &canboss_master->list[9]
#define canboss_master_ENTRY_H1011 &canboss_master->list[10]
#define canboss_master_ENTRY_H1012 &canboss_master->list[11]
#define canboss_master_ENTRY_H1014 &canboss_master->list[12]
#define canboss_master_ENTRY_H1015 &canboss_master->list[13]
#define canboss_master_ENTRY_H1016 &canboss_master->list[14]
#define canboss_master_ENTRY_H1017 &canboss_master->list[15]
#define canboss_master_ENTRY_H1018 &canboss_master->list[16]
#define canboss_master_ENTRY_H1019 &canboss_master->list[17]
#define canboss_master_ENTRY_H1200 &canboss_master->list[18]
#define canboss_master_ENTRY_H1280 &canboss_master->list[19]
#define canboss_master_ENTRY_H1400 &canboss_master->list[20]
#define canboss_master_ENTRY_H1401 &canboss_master->list[21]
#define canboss_master_ENTRY_H1402 &canboss_master->list[22]
#define canboss_master_ENTRY_H1403 &canboss_master->list[23]
#define canboss_master_ENTRY_H1404 &canboss_master->list[24]
#define canboss_master_ENTRY_H1405 &canboss_master->list[25]
#define canboss_master_ENTRY_H1406 &canboss_master->list[26]
#define canboss_master_ENTRY_H1600 &canboss_master->list[27]
#define canboss_master_ENTRY_H1601 &canboss_master->list[28]
#define canboss_master_ENTRY_H1602 &canboss_master->list[29]
#define canboss_master_ENTRY_H1603 &canboss_master->list[30]
#define canboss_master_ENTRY_H1604 &canboss_master->list[31]
#define canboss_master_ENTRY_H1605 &canboss_master->list[32]
#define canboss_master_ENTRY_H1606 &canboss_master->list[33]
#define canboss_master_ENTRY_H1800 &canboss_master->list[34]
#define canboss_master_ENTRY_H1801 &canboss_master->list[35]
#define canboss_master_ENTRY_H1A00 &canboss_master->list[36]
#define canboss_master_ENTRY_H1A01 &canboss_master->list[37]
#define canboss_master_ENTRY_H2110 &canboss_master->list[38]
#define canboss_master_ENTRY_H2111 &canboss_master->list[39]
#define canboss_master_ENTRY_H2112 &canboss_master->list[40]
#define canboss_master_ENTRY_H2120 &canboss_master->list[41]
#define canboss_master_ENTRY_H2121 &canboss_master->list[42]
#define canboss_master_ENTRY_H2130 &canboss_master->list[43]
#define canboss_master_ENTRY_H2131 &canboss_master->list[44]
#define canboss_master_ENTRY_H2132 &canboss_master->list[45]
#define canboss_master_ENTRY_H2210 &canboss_master->list[46]
#define canboss_master_ENTRY_H2220 &canboss_master->list[47]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define canboss_master_ENTRY_H1000_deviceType &canboss_master->list[0]
#define canboss_master_ENTRY_H1001_errorRegister &canboss_master->list[1]
#define canboss_master_ENTRY_H1003_pre_definedErrorField &canboss_master->list[2]
#define canboss_master_ENTRY_H1005_COB_ID_SYNCMessage &canboss_master->list[3]
#define canboss_master_ENTRY_H1006_communicationCyclePeriod &canboss_master->list[4]
#define canboss_master_ENTRY_H1007_synchronousWindowLength &canboss_master->list[5]
#define canboss_master_ENTRY_H1008_manufacturerDeviceName &canboss_master->list[6]
#define canboss_master_ENTRY_H1009_manufacturerHardwareVersion &canboss_master->list[7]
#define canboss_master_ENTRY_H100A_manufacturerSoftwareVersion &canboss_master->list[8]
#define canboss_master_ENTRY_H1010_storeParameters &canboss_master->list[9]
#define canboss_master_ENTRY_H1011_restoreDefaultParameters &canboss_master->list[10]
#define canboss_master_ENTRY_H1012_COB_IDTimeStampObject &canboss_master->list[11]
#define canboss_master_ENTRY_H1014_COB_ID_EMCY &canboss_master->list[12]
#define canboss_master_ENTRY_H1015_inhibitTimeEMCY &canboss_master->list[13]
#define canboss_master_ENTRY_H1016_consumerHeartbeatTime &canboss_master->list[14]
#define canboss_master_ENTRY_H1017_producerHeartbeatTime &canboss_master->list[15]
#define canboss_master_ENTRY_H1018_identity &canboss_master->list[16]
#define canboss_master_ENTRY_H1019_synchronousCounterOverflowValue &canboss_master->list[17]
#define canboss_master_ENTRY_H1200_SDOServerParameter &canboss_master->list[18]
#define canboss_master_ENTRY_H1280_SDOClientParameter &canboss_master->list[19]
#define canboss_master_ENTRY_H1400_RPDOCommunicationParameter &canboss_master->list[20]
#define canboss_master_ENTRY_H1401_RPDOCommunicationParameter &canboss_master->list[21]
#define canboss_master_ENTRY_H1402_RPDOCommunicationParameter &canboss_master->list[22]
#define canboss_master_ENTRY_H1403_RPDOCommunicationParameter &canboss_master->list[23]
#define canboss_master_ENTRY_H1404_RPDOCommunicationParameter &canboss_master->list[24]
#define canboss_master_ENTRY_H1405_RPDOCommunicationParameter &canboss_master->list[25]
#define canboss_master_ENTRY_H1406_RPDOCommunicationParameter &canboss_master->list[26]
#define canboss_master_ENTRY_H1600_RPDOMappingParameter &canboss_master->list[27]
#define canboss_master_ENTRY_H1601_RPDOMappingParameter &canboss_master->list[28]
#define canboss_master_ENTRY_H1602_RPDOMappingParameter &canboss_master->list[29]
#define canboss_master_ENTRY_H1603_RPDOMappingParameter &canboss_master->list[30]
#define canboss_master_ENTRY_H1604_RPDOMappingParameter &canboss_master->list[31]
#define canboss_master_ENTRY_H1605_RPDOMappingParameter &canboss_master->list[32]
#define canboss_master_ENTRY_H1606_RPDOMappingParameter &canboss_master->list[33]
#define canboss_master_ENTRY_H1800_TPDOCommunicationParameter &canboss_master->list[34]
#define canboss_master_ENTRY_H1801_TPDOCommunicationParameter &canboss_master->list[35]
#define canboss_master_ENTRY_H1A00_TPDOMappingParameter &canboss_master->list[36]
#define canboss_master_ENTRY_H1A01_TPDOMappingParameter &canboss_master->list[37]
#define canboss_master_ENTRY_H2110_IO_AnalogeEingaenge &canboss_master->list[38]
#define canboss_master_ENTRY_H2111_IO_Temperatur &canboss_master->list[39]
#define canboss_master_ENTRY_H2112_IO_DigitaleEingaenge &canboss_master->list[40]
#define canboss_master_ENTRY_H2120_antriebStatus &canboss_master->list[41]
#define canboss_master_ENTRY_H2121_antriebMesswerte &canboss_master->list[42]
#define canboss_master_ENTRY_H2130_sensorKlima &canboss_master->list[43]
#define canboss_master_ENTRY_H2131_sensorUmgebung &canboss_master->list[44]
#define canboss_master_ENTRY_H2132_sensorAlarm &canboss_master->list[45]
#define canboss_master_ENTRY_H2210_IO_Kommando &canboss_master->list[46]
#define canboss_master_ENTRY_H2220_antriebKommando &canboss_master->list[47]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define canboss_master_INIT_CONFIG(config) {\
    (config).CNT_NMT = canboss_master_CNT_NMT;\
    (config).ENTRY_H1017 = canboss_master_ENTRY_H1017;\
    (config).CNT_HB_CONS = canboss_master_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = canboss_master_CNT_ARR_1016;\
    (config).ENTRY_H1016 = canboss_master_ENTRY_H1016;\
    (config).CNT_EM = canboss_master_CNT_EM;\
    (config).ENTRY_H1001 = canboss_master_ENTRY_H1001;\
    (config).ENTRY_H1014 = canboss_master_ENTRY_H1014;\
    (config).ENTRY_H1015 = canboss_master_ENTRY_H1015;\
    (config).CNT_ARR_1003 = canboss_master_CNT_ARR_1003;\
    (config).ENTRY_H1003 = canboss_master_ENTRY_H1003;\
    (config).CNT_SDO_SRV = canboss_master_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = canboss_master_ENTRY_H1200;\
    (config).CNT_SDO_CLI = canboss_master_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = canboss_master_ENTRY_H1280;\
    (config).CNT_TIME = canboss_master_CNT_TIME;\
    (config).ENTRY_H1012 = canboss_master_ENTRY_H1012;\
    (config).CNT_SYNC = canboss_master_CNT_SYNC;\
    (config).ENTRY_H1005 = canboss_master_ENTRY_H1005;\
    (config).ENTRY_H1006 = canboss_master_ENTRY_H1006;\
    (config).ENTRY_H1007 = canboss_master_ENTRY_H1007;\
    (config).ENTRY_H1019 = canboss_master_ENTRY_H1019;\
    (config).CNT_RPDO = canboss_master_CNT_RPDO;\
    (config).ENTRY_H1400 = canboss_master_ENTRY_H1400;\
    (config).ENTRY_H1600 = canboss_master_ENTRY_H1600;\
    (config).CNT_TPDO = canboss_master_CNT_TPDO;\
    (config).ENTRY_H1800 = canboss_master_ENTRY_H1800;\
    (config).ENTRY_H1A00 = canboss_master_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* canboss_master_H */
