/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-1-g7357994-dirty+7357994f8ca5cb5d1a8699245e834022c176cb0d

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   demo_io.h; demo_io.c
        Project File: demo_io.eds
        File Version: 1

        Created:      07/14/2026 12:00:00
        Created By:   Protronic
        Modified:     07/14/2026 12:00:00
        Modified By:  Protronic

    Device Info:
        Vendor Name:  Protronic
        Vendor ID:    0
        Product Name: Demo-IO
        Product ID:   0

        Description:  Demo-Netzwerk: IO-Modul (digitale Ausgaenge, analoge Eingaenge, Temperatur), Node 16
*******************************************************************************/

#ifndef demo_io_H
#define demo_io_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define demo_io_CNT_NMT 1
#define demo_io_CNT_EM 1
#define demo_io_CNT_EM_PROD 1
#define demo_io_CNT_HB_PROD 1
#define demo_io_CNT_SDO_SRV 1
#define demo_io_CNT_RPDO 1
#define demo_io_CNT_TPDO 2


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define demo_io_CNT_ARR_2000 4
#define demo_io_CNT_ARR_2001 4
#define demo_io_CNT_ARR_2003 4


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
    } x1A01_TPDOMappingParameter;
    char x2102_geraetename[8];
    uint16_t x2103_filterzeitMs;
} demo_io_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    char x1008_manufacturerDeviceName[8];
    char x1009_manufacturerHardwareVersion[4];
    char x100A_manufacturerSoftwareVersion[4];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    uint8_t x2000_digitaleAusgaenge_sub0;
    bool_t x2000_digitaleAusgaenge[demo_io_CNT_ARR_2000];
    uint8_t x2001_analogeEingaenge_sub0;
    int16_t x2001_analogeEingaenge[demo_io_CNT_ARR_2001];
    uint8_t x2002_digitaleAusgaengeMaske;
    uint8_t x2003_digitaleEingaenge_sub0;
    bool_t x2003_digitaleEingaenge[demo_io_CNT_ARR_2003];
    float32_t x2100_temperatur;
    int16_t x2101_sollwert;
} demo_io_RAM_t;

#ifndef demo_io_ATTR_PERSIST_COMM
#define demo_io_ATTR_PERSIST_COMM
#endif
extern demo_io_ATTR_PERSIST_COMM demo_io_PERSIST_COMM_t demo_io_PERSIST_COMM;

#ifndef demo_io_ATTR_RAM
#define demo_io_ATTR_RAM
#endif
extern demo_io_ATTR_RAM demo_io_RAM_t demo_io_RAM;

#ifndef demo_io_ATTR_OD
#define demo_io_ATTR_OD
#endif
extern demo_io_ATTR_OD OD_t *demo_io;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define demo_io_ENTRY_H1000 &demo_io->list[0]
#define demo_io_ENTRY_H1001 &demo_io->list[1]
#define demo_io_ENTRY_H1008 &demo_io->list[2]
#define demo_io_ENTRY_H1009 &demo_io->list[3]
#define demo_io_ENTRY_H100A &demo_io->list[4]
#define demo_io_ENTRY_H1014 &demo_io->list[5]
#define demo_io_ENTRY_H1015 &demo_io->list[6]
#define demo_io_ENTRY_H1017 &demo_io->list[7]
#define demo_io_ENTRY_H1018 &demo_io->list[8]
#define demo_io_ENTRY_H1200 &demo_io->list[9]
#define demo_io_ENTRY_H1400 &demo_io->list[10]
#define demo_io_ENTRY_H1600 &demo_io->list[11]
#define demo_io_ENTRY_H1800 &demo_io->list[12]
#define demo_io_ENTRY_H1801 &demo_io->list[13]
#define demo_io_ENTRY_H1A00 &demo_io->list[14]
#define demo_io_ENTRY_H1A01 &demo_io->list[15]
#define demo_io_ENTRY_H2000 &demo_io->list[16]
#define demo_io_ENTRY_H2001 &demo_io->list[17]
#define demo_io_ENTRY_H2002 &demo_io->list[18]
#define demo_io_ENTRY_H2003 &demo_io->list[19]
#define demo_io_ENTRY_H2100 &demo_io->list[20]
#define demo_io_ENTRY_H2101 &demo_io->list[21]
#define demo_io_ENTRY_H2102 &demo_io->list[22]
#define demo_io_ENTRY_H2103 &demo_io->list[23]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define demo_io_ENTRY_H1000_deviceType &demo_io->list[0]
#define demo_io_ENTRY_H1001_errorRegister &demo_io->list[1]
#define demo_io_ENTRY_H1008_manufacturerDeviceName &demo_io->list[2]
#define demo_io_ENTRY_H1009_manufacturerHardwareVersion &demo_io->list[3]
#define demo_io_ENTRY_H100A_manufacturerSoftwareVersion &demo_io->list[4]
#define demo_io_ENTRY_H1014_COB_ID_EMCY &demo_io->list[5]
#define demo_io_ENTRY_H1015_inhibitTimeEMCY &demo_io->list[6]
#define demo_io_ENTRY_H1017_producerHeartbeatTime &demo_io->list[7]
#define demo_io_ENTRY_H1018_identity &demo_io->list[8]
#define demo_io_ENTRY_H1200_SDOServerParameter &demo_io->list[9]
#define demo_io_ENTRY_H1400_RPDOCommunicationParameter &demo_io->list[10]
#define demo_io_ENTRY_H1600_RPDOMappingParameter &demo_io->list[11]
#define demo_io_ENTRY_H1800_TPDOCommunicationParameter &demo_io->list[12]
#define demo_io_ENTRY_H1801_TPDOCommunicationParameter &demo_io->list[13]
#define demo_io_ENTRY_H1A00_TPDOMappingParameter &demo_io->list[14]
#define demo_io_ENTRY_H1A01_TPDOMappingParameter &demo_io->list[15]
#define demo_io_ENTRY_H2000_digitaleAusgaenge &demo_io->list[16]
#define demo_io_ENTRY_H2001_analogeEingaenge &demo_io->list[17]
#define demo_io_ENTRY_H2002_digitaleAusgaengeMaske &demo_io->list[18]
#define demo_io_ENTRY_H2003_digitaleEingaenge &demo_io->list[19]
#define demo_io_ENTRY_H2100_temperatur &demo_io->list[20]
#define demo_io_ENTRY_H2101_sollwert &demo_io->list[21]
#define demo_io_ENTRY_H2102_geraetename &demo_io->list[22]
#define demo_io_ENTRY_H2103_filterzeitMs &demo_io->list[23]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define demo_io_INIT_CONFIG(config) {\
    (config).CNT_NMT = demo_io_CNT_NMT;\
    (config).ENTRY_H1017 = demo_io_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = demo_io_CNT_EM;\
    (config).ENTRY_H1001 = demo_io_ENTRY_H1001;\
    (config).ENTRY_H1014 = demo_io_ENTRY_H1014;\
    (config).ENTRY_H1015 = demo_io_ENTRY_H1015;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = demo_io_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = demo_io_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = demo_io_CNT_RPDO;\
    (config).ENTRY_H1400 = demo_io_ENTRY_H1400;\
    (config).ENTRY_H1600 = demo_io_ENTRY_H1600;\
    (config).CNT_TPDO = demo_io_CNT_TPDO;\
    (config).ENTRY_H1800 = demo_io_ENTRY_H1800;\
    (config).ENTRY_H1A00 = demo_io_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* demo_io_H */
