/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-1-g7357994-dirty+7357994f8ca5cb5d1a8699245e834022c176cb0d

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "demo_io.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
demo_io_ATTR_PERSIST_COMM demo_io_PERSIST_COMM_t demo_io_PERSIST_COMM = {
    .x1000_deviceType = 0x00060191,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00010010,
        .revisionNumber = 0x00010000,
        .serialNumber = 0x00000000
    },
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000200,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x05,
        .applicationObject1 = 0x20000108,
        .applicationObject2 = 0x20000208,
        .applicationObject3 = 0x20000308,
        .applicationObject4 = 0x20000408,
        .applicationObject5 = 0x21010010
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000180,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0064,
        .eventTimer = 0x00C8,
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000280,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0064,
        .eventTimer = 0x03E8,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x20010110,
        .applicationObject2 = 0x20010210,
        .applicationObject3 = 0x20010310,
        .applicationObject4 = 0x20010410
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x05,
        .applicationObject1 = 0x21000020,
        .applicationObject2 = 0x20030108,
        .applicationObject3 = 0x20030208,
        .applicationObject4 = 0x20030308,
        .applicationObject5 = 0x20030408
    },
    .x2102_geraetename = {'D', 'e', 'm', 'o', '-', 'I', 'O', 0},
    .x2103_filterzeitMs = 0x000A
};

demo_io_ATTR_RAM demo_io_RAM_t demo_io_RAM = {
    .x1001_errorRegister = 0x00,
    .x1008_manufacturerDeviceName = {'D', 'e', 'm', 'o', '-', 'I', 'O', 0},
    .x1009_manufacturerHardwareVersion = {'1', '.', '0', 0},
    .x100A_manufacturerSoftwareVersion = {'1', '.', '0', 0},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x2000_digitaleAusgaenge_sub0 = 0x04,
    .x2000_digitaleAusgaenge = {false, false, false, false},
    .x2001_analogeEingaenge_sub0 = 0x04,
    .x2001_analogeEingaenge = {0, 0, 0, 0},
    .x2002_digitaleAusgaengeMaske = 0x00,
    .x2003_digitaleEingaenge_sub0 = 0x04,
    .x2003_digitaleEingaenge = {false, false, false, false},
    .x2100_temperatur = 0.0,
    .x2101_sollwert = 0
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[6];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[5];
    OD_obj_record_t o_1A01_TPDOMappingParameter[6];
    OD_obj_array_t o_2000_digitaleAusgaenge;
    OD_obj_array_t o_2001_analogeEingaenge;
    OD_obj_var_t o_2002_digitaleAusgaengeMaske;
    OD_obj_array_t o_2003_digitaleEingaenge;
    OD_obj_var_t o_2100_temperatur;
    OD_obj_var_t o_2101_sollwert;
    OD_obj_var_t o_2102_geraetename;
    OD_obj_var_t o_2103_filterzeitMs;
} demo_ioObjs_t;

static CO_PROGMEM demo_ioObjs_t demo_ioObjs = {
    .o_1000_deviceType = {
        .dataOrig = &demo_io_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &demo_io_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &demo_io_RAM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 7
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &demo_io_RAM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 3
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &demo_io_RAM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 3
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &demo_io_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &demo_io_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &demo_io_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &demo_io_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_io_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2000_digitaleAusgaenge = {
        .dataOrig0 = &demo_io_RAM.x2000_digitaleAusgaenge_sub0,
        .dataOrig = &demo_io_RAM.x2000_digitaleAusgaenge[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_2001_analogeEingaenge = {
        .dataOrig0 = &demo_io_RAM.x2001_analogeEingaenge_sub0,
        .dataOrig = &demo_io_RAM.x2001_analogeEingaenge[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2002_digitaleAusgaengeMaske = {
        .dataOrig = &demo_io_RAM.x2002_digitaleAusgaengeMaske,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_2003_digitaleEingaenge = {
        .dataOrig0 = &demo_io_RAM.x2003_digitaleEingaenge_sub0,
        .dataOrig = &demo_io_RAM.x2003_digitaleEingaenge[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_2100_temperatur = {
        .dataOrig = &demo_io_RAM.x2100_temperatur,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2101_sollwert = {
        .dataOrig = &demo_io_RAM.x2101_sollwert,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2102_geraetename = {
        .dataOrig = &demo_io_PERSIST_COMM.x2102_geraetename[0],
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 7
    },
    .o_2103_filterzeitMs = {
        .dataOrig = &demo_io_PERSIST_COMM.x2103_filterzeitMs,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static demo_io_ATTR_OD OD_entry_t demo_ioList[] = {
    {0x1000, 0x01, ODT_VAR, &demo_ioObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &demo_ioObjs.o_1001_errorRegister, NULL},
    {0x1008, 0x01, ODT_VAR, &demo_ioObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &demo_ioObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &demo_ioObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1014, 0x01, ODT_VAR, &demo_ioObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &demo_ioObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1017, 0x01, ODT_VAR, &demo_ioObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &demo_ioObjs.o_1018_identity, NULL},
    {0x1200, 0x03, ODT_REC, &demo_ioObjs.o_1200_SDOServerParameter, NULL},
    {0x1400, 0x04, ODT_REC, &demo_ioObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1600, 0x06, ODT_REC, &demo_ioObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &demo_ioObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &demo_ioObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x05, ODT_REC, &demo_ioObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x06, ODT_REC, &demo_ioObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x2000, 0x05, ODT_ARR, &demo_ioObjs.o_2000_digitaleAusgaenge, NULL},
    {0x2001, 0x05, ODT_ARR, &demo_ioObjs.o_2001_analogeEingaenge, NULL},
    {0x2002, 0x01, ODT_VAR, &demo_ioObjs.o_2002_digitaleAusgaengeMaske, NULL},
    {0x2003, 0x05, ODT_ARR, &demo_ioObjs.o_2003_digitaleEingaenge, NULL},
    {0x2100, 0x01, ODT_VAR, &demo_ioObjs.o_2100_temperatur, NULL},
    {0x2101, 0x01, ODT_VAR, &demo_ioObjs.o_2101_sollwert, NULL},
    {0x2102, 0x01, ODT_VAR, &demo_ioObjs.o_2102_geraetename, NULL},
    {0x2103, 0x01, ODT_VAR, &demo_ioObjs.o_2103_filterzeitMs, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _demo_io = {
    (sizeof(demo_ioList) / sizeof(demo_ioList[0])) - 1,
    &demo_ioList[0]
};

OD_t *demo_io = &_demo_io;
