/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-1-g7357994-dirty+7357994f8ca5cb5d1a8699245e834022c176cb0d

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "demo_drive.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
demo_drive_ATTR_PERSIST_COMM demo_drive_PERSIST_COMM_t demo_drive_PERSIST_COMM = {
    .x1000_deviceType = 0x00020192,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00010020,
        .revisionNumber = 0x00010000,
        .serialNumber = 0x00000000
    },
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000200,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x60400010,
        .applicationObject2 = 0x60420010,
        .applicationObject3 = 0x22010008
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000180,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0064,
        .eventTimer = 0x00C8,
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000280,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0064,
        .eventTimer = 0x03E8,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x60410010,
        .applicationObject2 = 0x60430010,
        .applicationObject3 = 0x60440010
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x22000020,
        .applicationObject2 = 0x22020020
    },
    .x6042_vlTargetVelocity = 0,
    .x6046_vlVelocityMinMaxAmount_sub0 = 0x02,
    .x6046_vlVelocityMinMaxAmount = {0x00000000, 0x00007530}
};

demo_drive_ATTR_RAM demo_drive_RAM_t demo_drive_RAM = {
    .x1001_errorRegister = 0x00,
    .x1008_manufacturerDeviceName = {'D', 'e', 'm', 'o', '-', 'A', 'n', 't', 'r', 'i', 'e', 'b', 0},
    .x1009_manufacturerHardwareVersion = {'1', '.', '0', 0},
    .x100A_manufacturerSoftwareVersion = {'1', '.', '0', 0},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x2200_motorstromMA = 0,
    .x2201_bremseAktiv = false,
    .x2202_temperaturEndstufe = 0.0,
    .x6040_controlword = 0x0000,
    .x6041_statusword = 0x0000,
    .x6043_vlVelocityDemand = 0,
    .x6044_vlVelocityActualValue = 0
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[4];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[4];
    OD_obj_record_t o_1A01_TPDOMappingParameter[3];
    OD_obj_var_t o_2200_motorstromMA;
    OD_obj_var_t o_2201_bremseAktiv;
    OD_obj_var_t o_2202_temperaturEndstufe;
    OD_obj_var_t o_6040_controlword;
    OD_obj_var_t o_6041_statusword;
    OD_obj_var_t o_6042_vlTargetVelocity;
    OD_obj_var_t o_6043_vlVelocityDemand;
    OD_obj_var_t o_6044_vlVelocityActualValue;
    OD_obj_array_t o_6046_vlVelocityMinMaxAmount;
} demo_driveObjs_t;

static CO_PROGMEM demo_driveObjs_t demo_driveObjs = {
    .o_1000_deviceType = {
        .dataOrig = &demo_drive_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &demo_drive_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &demo_drive_RAM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 12
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &demo_drive_RAM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 3
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &demo_drive_RAM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 3
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &demo_drive_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &demo_drive_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &demo_drive_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &demo_drive_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &demo_drive_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2200_motorstromMA = {
        .dataOrig = &demo_drive_RAM.x2200_motorstromMA,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2201_bremseAktiv = {
        .dataOrig = &demo_drive_RAM.x2201_bremseAktiv,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_2202_temperaturEndstufe = {
        .dataOrig = &demo_drive_RAM.x2202_temperaturEndstufe,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6040_controlword = {
        .dataOrig = &demo_drive_RAM.x6040_controlword,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_statusword = {
        .dataOrig = &demo_drive_RAM.x6041_statusword,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6042_vlTargetVelocity = {
        .dataOrig = &demo_drive_PERSIST_COMM.x6042_vlTargetVelocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6043_vlVelocityDemand = {
        .dataOrig = &demo_drive_RAM.x6043_vlVelocityDemand,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6044_vlVelocityActualValue = {
        .dataOrig = &demo_drive_RAM.x6044_vlVelocityActualValue,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6046_vlVelocityMinMaxAmount = {
        .dataOrig0 = &demo_drive_PERSIST_COMM.x6046_vlVelocityMinMaxAmount_sub0,
        .dataOrig = &demo_drive_PERSIST_COMM.x6046_vlVelocityMinMaxAmount[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static demo_drive_ATTR_OD OD_entry_t demo_driveList[] = {
    {0x1000, 0x01, ODT_VAR, &demo_driveObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &demo_driveObjs.o_1001_errorRegister, NULL},
    {0x1008, 0x01, ODT_VAR, &demo_driveObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &demo_driveObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &demo_driveObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1014, 0x01, ODT_VAR, &demo_driveObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &demo_driveObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1017, 0x01, ODT_VAR, &demo_driveObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &demo_driveObjs.o_1018_identity, NULL},
    {0x1200, 0x03, ODT_REC, &demo_driveObjs.o_1200_SDOServerParameter, NULL},
    {0x1400, 0x04, ODT_REC, &demo_driveObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1600, 0x04, ODT_REC, &demo_driveObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &demo_driveObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &demo_driveObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x04, ODT_REC, &demo_driveObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x03, ODT_REC, &demo_driveObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x2200, 0x01, ODT_VAR, &demo_driveObjs.o_2200_motorstromMA, NULL},
    {0x2201, 0x01, ODT_VAR, &demo_driveObjs.o_2201_bremseAktiv, NULL},
    {0x2202, 0x01, ODT_VAR, &demo_driveObjs.o_2202_temperaturEndstufe, NULL},
    {0x6040, 0x01, ODT_VAR, &demo_driveObjs.o_6040_controlword, NULL},
    {0x6041, 0x01, ODT_VAR, &demo_driveObjs.o_6041_statusword, NULL},
    {0x6042, 0x01, ODT_VAR, &demo_driveObjs.o_6042_vlTargetVelocity, NULL},
    {0x6043, 0x01, ODT_VAR, &demo_driveObjs.o_6043_vlVelocityDemand, NULL},
    {0x6044, 0x01, ODT_VAR, &demo_driveObjs.o_6044_vlVelocityActualValue, NULL},
    {0x6046, 0x03, ODT_ARR, &demo_driveObjs.o_6046_vlVelocityMinMaxAmount, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _demo_drive = {
    (sizeof(demo_driveList) / sizeof(demo_driveList[0])) - 1,
    &demo_driveList[0]
};

OD_t *demo_drive = &_demo_drive;
