/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-1-g7357994-dirty+7357994f8ca5cb5d1a8699245e834022c176cb0d

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   demo_drive.h; demo_drive.c
        Project File: demo_drive.eds
        File Version: 1

        Created:      07/14/2026 12:00:00
        Created By:   Protronic
        Modified:     07/14/2026 12:00:00
        Modified By:  Protronic

    Device Info:
        Vendor Name:  Protronic
        Vendor ID:    0
        Product Name: Demo-Antrieb
        Product ID:   0

        Description:  Demo-Netzwerk: Antrieb (CiA402-Teilmenge, vl velocity mode), Node 32
*******************************************************************************/

#ifndef demo_drive_H
#define demo_drive_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define demo_drive_CNT_NMT 1
#define demo_drive_CNT_EM 1
#define demo_drive_CNT_EM_PROD 1
#define demo_drive_CNT_HB_PROD 1
#define demo_drive_CNT_SDO_SRV 1
#define demo_drive_CNT_RPDO 1
#define demo_drive_CNT_TPDO 2


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define demo_drive_CNT_ARR_6046 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1A01_TPDOMappingParameter;
    int16_t x6042_vlTargetVelocity;
    uint8_t x6046_vlVelocityMinMaxAmount_sub0;
    uint32_t x6046_vlVelocityMinMaxAmount[demo_drive_CNT_ARR_6046];
} demo_drive_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    char x1008_manufacturerDeviceName[13];
    char x1009_manufacturerHardwareVersion[4];
    char x100A_manufacturerSoftwareVersion[4];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    int32_t x2200_motorstromMA;
    bool_t x2201_bremseAktiv;
    float32_t x2202_temperaturEndstufe;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int16_t x6043_vlVelocityDemand;
    int16_t x6044_vlVelocityActualValue;
} demo_drive_RAM_t;

#ifndef demo_drive_ATTR_PERSIST_COMM
#define demo_drive_ATTR_PERSIST_COMM
#endif
extern demo_drive_ATTR_PERSIST_COMM demo_drive_PERSIST_COMM_t demo_drive_PERSIST_COMM;

#ifndef demo_drive_ATTR_RAM
#define demo_drive_ATTR_RAM
#endif
extern demo_drive_ATTR_RAM demo_drive_RAM_t demo_drive_RAM;

#ifndef demo_drive_ATTR_OD
#define demo_drive_ATTR_OD
#endif
extern demo_drive_ATTR_OD OD_t *demo_drive;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define demo_drive_ENTRY_H1000 &demo_drive->list[0]
#define demo_drive_ENTRY_H1001 &demo_drive->list[1]
#define demo_drive_ENTRY_H1008 &demo_drive->list[2]
#define demo_drive_ENTRY_H1009 &demo_drive->list[3]
#define demo_drive_ENTRY_H100A &demo_drive->list[4]
#define demo_drive_ENTRY_H1014 &demo_drive->list[5]
#define demo_drive_ENTRY_H1015 &demo_drive->list[6]
#define demo_drive_ENTRY_H1017 &demo_drive->list[7]
#define demo_drive_ENTRY_H1018 &demo_drive->list[8]
#define demo_drive_ENTRY_H1200 &demo_drive->list[9]
#define demo_drive_ENTRY_H1400 &demo_drive->list[10]
#define demo_drive_ENTRY_H1600 &demo_drive->list[11]
#define demo_drive_ENTRY_H1800 &demo_drive->list[12]
#define demo_drive_ENTRY_H1801 &demo_drive->list[13]
#define demo_drive_ENTRY_H1A00 &demo_drive->list[14]
#define demo_drive_ENTRY_H1A01 &demo_drive->list[15]
#define demo_drive_ENTRY_H2200 &demo_drive->list[16]
#define demo_drive_ENTRY_H2201 &demo_drive->list[17]
#define demo_drive_ENTRY_H2202 &demo_drive->list[18]
#define demo_drive_ENTRY_H6040 &demo_drive->list[19]
#define demo_drive_ENTRY_H6041 &demo_drive->list[20]
#define demo_drive_ENTRY_H6042 &demo_drive->list[21]
#define demo_drive_ENTRY_H6043 &demo_drive->list[22]
#define demo_drive_ENTRY_H6044 &demo_drive->list[23]
#define demo_drive_ENTRY_H6046 &demo_drive->list[24]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define demo_drive_ENTRY_H1000_deviceType &demo_drive->list[0]
#define demo_drive_ENTRY_H1001_errorRegister &demo_drive->list[1]
#define demo_drive_ENTRY_H1008_manufacturerDeviceName &demo_drive->list[2]
#define demo_drive_ENTRY_H1009_manufacturerHardwareVersion &demo_drive->list[3]
#define demo_drive_ENTRY_H100A_manufacturerSoftwareVersion &demo_drive->list[4]
#define demo_drive_ENTRY_H1014_COB_ID_EMCY &demo_drive->list[5]
#define demo_drive_ENTRY_H1015_inhibitTimeEMCY &demo_drive->list[6]
#define demo_drive_ENTRY_H1017_producerHeartbeatTime &demo_drive->list[7]
#define demo_drive_ENTRY_H1018_identity &demo_drive->list[8]
#define demo_drive_ENTRY_H1200_SDOServerParameter &demo_drive->list[9]
#define demo_drive_ENTRY_H1400_RPDOCommunicationParameter &demo_drive->list[10]
#define demo_drive_ENTRY_H1600_RPDOMappingParameter &demo_drive->list[11]
#define demo_drive_ENTRY_H1800_TPDOCommunicationParameter &demo_drive->list[12]
#define demo_drive_ENTRY_H1801_TPDOCommunicationParameter &demo_drive->list[13]
#define demo_drive_ENTRY_H1A00_TPDOMappingParameter &demo_drive->list[14]
#define demo_drive_ENTRY_H1A01_TPDOMappingParameter &demo_drive->list[15]
#define demo_drive_ENTRY_H2200_motorstromMA &demo_drive->list[16]
#define demo_drive_ENTRY_H2201_bremseAktiv &demo_drive->list[17]
#define demo_drive_ENTRY_H2202_temperaturEndstufe &demo_drive->list[18]
#define demo_drive_ENTRY_H6040_controlword &demo_drive->list[19]
#define demo_drive_ENTRY_H6041_statusword &demo_drive->list[20]
#define demo_drive_ENTRY_H6042_vlTargetVelocity &demo_drive->list[21]
#define demo_drive_ENTRY_H6043_vlVelocityDemand &demo_drive->list[22]
#define demo_drive_ENTRY_H6044_vlVelocityActualValue &demo_drive->list[23]
#define demo_drive_ENTRY_H6046_vlVelocityMinMaxAmount &demo_drive->list[24]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define demo_drive_INIT_CONFIG(config) {\
    (config).CNT_NMT = demo_drive_CNT_NMT;\
    (config).ENTRY_H1017 = demo_drive_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = demo_drive_CNT_EM;\
    (config).ENTRY_H1001 = demo_drive_ENTRY_H1001;\
    (config).ENTRY_H1014 = demo_drive_ENTRY_H1014;\
    (config).ENTRY_H1015 = demo_drive_ENTRY_H1015;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = demo_drive_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = demo_drive_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = demo_drive_CNT_RPDO;\
    (config).ENTRY_H1400 = demo_drive_ENTRY_H1400;\
    (config).ENTRY_H1600 = demo_drive_ENTRY_H1600;\
    (config).CNT_TPDO = demo_drive_CNT_TPDO;\
    (config).ENTRY_H1800 = demo_drive_ENTRY_H1800;\
    (config).ENTRY_H1A00 = demo_drive_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* demo_drive_H */
