/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-1-g7357994-dirty+7357994f8ca5cb5d1a8699245e834022c176cb0d

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   demo_sensor.h; demo_sensor.c
        Project File: demo_sensor.eds
        File Version: 1

        Created:      07/14/2026 12:00:00
        Created By:   Protronic
        Modified:     07/14/2026 12:00:00
        Modified By:  Protronic

    Device Info:
        Vendor Name:  Protronic
        Vendor ID:    0
        Product Name: Demo-Sensor
        Product ID:   0

        Description:  Demo-Netzwerk: Klimasensor (Temperatur, Feuchte, Druck, Alarm), Node 48
*******************************************************************************/

#ifndef demo_sensor_H
#define demo_sensor_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define demo_sensor_CNT_NMT 1
#define demo_sensor_CNT_EM 1
#define demo_sensor_CNT_EM_PROD 1
#define demo_sensor_CNT_HB_PROD 1
#define demo_sensor_CNT_SDO_SRV 1
#define demo_sensor_CNT_TPDO 3


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1A02_TPDOMappingParameter;
    uint16_t x2303_messintervallMs;
    struct {
        uint8_t highestSub_indexSupported;
        float32_t temperaturMax;
        float32_t relativeFeuchteMax;
    } x2304_grenzwerte;
} demo_sensor_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    char x1008_manufacturerDeviceName[12];
    char x1009_manufacturerHardwareVersion[4];
    char x100A_manufacturerSoftwareVersion[4];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    struct {
        uint8_t highestSub_indexSupported;
        float32_t temperatur;
        float32_t relativeFeuchte;
    } x2300_klima;
    struct {
        uint8_t highestSub_indexSupported;
        float32_t luftdruckHPa;
        uint32_t messzaehler;
    } x2301_umgebung;
    uint8_t x2302_alarmstatus;
    bool_t x2305_alarmAktiv;
} demo_sensor_RAM_t;

#ifndef demo_sensor_ATTR_PERSIST_COMM
#define demo_sensor_ATTR_PERSIST_COMM
#endif
extern demo_sensor_ATTR_PERSIST_COMM demo_sensor_PERSIST_COMM_t demo_sensor_PERSIST_COMM;

#ifndef demo_sensor_ATTR_RAM
#define demo_sensor_ATTR_RAM
#endif
extern demo_sensor_ATTR_RAM demo_sensor_RAM_t demo_sensor_RAM;

#ifndef demo_sensor_ATTR_OD
#define demo_sensor_ATTR_OD
#endif
extern demo_sensor_ATTR_OD OD_t *demo_sensor;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define demo_sensor_ENTRY_H1000 &demo_sensor->list[0]
#define demo_sensor_ENTRY_H1001 &demo_sensor->list[1]
#define demo_sensor_ENTRY_H1008 &demo_sensor->list[2]
#define demo_sensor_ENTRY_H1009 &demo_sensor->list[3]
#define demo_sensor_ENTRY_H100A &demo_sensor->list[4]
#define demo_sensor_ENTRY_H1014 &demo_sensor->list[5]
#define demo_sensor_ENTRY_H1015 &demo_sensor->list[6]
#define demo_sensor_ENTRY_H1017 &demo_sensor->list[7]
#define demo_sensor_ENTRY_H1018 &demo_sensor->list[8]
#define demo_sensor_ENTRY_H1200 &demo_sensor->list[9]
#define demo_sensor_ENTRY_H1800 &demo_sensor->list[10]
#define demo_sensor_ENTRY_H1801 &demo_sensor->list[11]
#define demo_sensor_ENTRY_H1802 &demo_sensor->list[12]
#define demo_sensor_ENTRY_H1A00 &demo_sensor->list[13]
#define demo_sensor_ENTRY_H1A01 &demo_sensor->list[14]
#define demo_sensor_ENTRY_H1A02 &demo_sensor->list[15]
#define demo_sensor_ENTRY_H2300 &demo_sensor->list[16]
#define demo_sensor_ENTRY_H2301 &demo_sensor->list[17]
#define demo_sensor_ENTRY_H2302 &demo_sensor->list[18]
#define demo_sensor_ENTRY_H2303 &demo_sensor->list[19]
#define demo_sensor_ENTRY_H2304 &demo_sensor->list[20]
#define demo_sensor_ENTRY_H2305 &demo_sensor->list[21]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define demo_sensor_ENTRY_H1000_deviceType &demo_sensor->list[0]
#define demo_sensor_ENTRY_H1001_errorRegister &demo_sensor->list[1]
#define demo_sensor_ENTRY_H1008_manufacturerDeviceName &demo_sensor->list[2]
#define demo_sensor_ENTRY_H1009_manufacturerHardwareVersion &demo_sensor->list[3]
#define demo_sensor_ENTRY_H100A_manufacturerSoftwareVersion &demo_sensor->list[4]
#define demo_sensor_ENTRY_H1014_COB_ID_EMCY &demo_sensor->list[5]
#define demo_sensor_ENTRY_H1015_inhibitTimeEMCY &demo_sensor->list[6]
#define demo_sensor_ENTRY_H1017_producerHeartbeatTime &demo_sensor->list[7]
#define demo_sensor_ENTRY_H1018_identity &demo_sensor->list[8]
#define demo_sensor_ENTRY_H1200_SDOServerParameter &demo_sensor->list[9]
#define demo_sensor_ENTRY_H1800_TPDOCommunicationParameter &demo_sensor->list[10]
#define demo_sensor_ENTRY_H1801_TPDOCommunicationParameter &demo_sensor->list[11]
#define demo_sensor_ENTRY_H1802_TPDOCommunicationParameter &demo_sensor->list[12]
#define demo_sensor_ENTRY_H1A00_TPDOMappingParameter &demo_sensor->list[13]
#define demo_sensor_ENTRY_H1A01_TPDOMappingParameter &demo_sensor->list[14]
#define demo_sensor_ENTRY_H1A02_TPDOMappingParameter &demo_sensor->list[15]
#define demo_sensor_ENTRY_H2300_klima &demo_sensor->list[16]
#define demo_sensor_ENTRY_H2301_umgebung &demo_sensor->list[17]
#define demo_sensor_ENTRY_H2302_alarmstatus &demo_sensor->list[18]
#define demo_sensor_ENTRY_H2303_messintervallMs &demo_sensor->list[19]
#define demo_sensor_ENTRY_H2304_grenzwerte &demo_sensor->list[20]
#define demo_sensor_ENTRY_H2305_alarmAktiv &demo_sensor->list[21]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define demo_sensor_INIT_CONFIG(config) {\
    (config).CNT_NMT = demo_sensor_CNT_NMT;\
    (config).ENTRY_H1017 = demo_sensor_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = demo_sensor_CNT_EM;\
    (config).ENTRY_H1001 = demo_sensor_ENTRY_H1001;\
    (config).ENTRY_H1014 = demo_sensor_ENTRY_H1014;\
    (config).ENTRY_H1015 = demo_sensor_ENTRY_H1015;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = demo_sensor_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = demo_sensor_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = NULL;\
    (config).ENTRY_H1600 = NULL;\
    (config).CNT_TPDO = demo_sensor_CNT_TPDO;\
    (config).ENTRY_H1800 = demo_sensor_ENTRY_H1800;\
    (config).ENTRY_H1A00 = demo_sensor_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* demo_sensor_H */
