/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-1-g7357994-dirty+7357994f8ca5cb5d1a8699245e834022c176cb0d

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "canboss_master.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
canboss_master_ATTR_PERSIST_COMM canboss_master_PERSIST_COMM_t canboss_master_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00100BB8, 0x00200BB8, 0x00300BB8, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x000100FF,
        .revisionNumber = 0x00010000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000190,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1401_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000290,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1402_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x000001A0,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1403_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x000002A0,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1404_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x000001B0,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1405_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x000002B0,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1406_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x000003B0,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x21100110,
        .applicationObject2 = 0x21100210,
        .applicationObject3 = 0x21100310,
        .applicationObject4 = 0x21100410
    },
    .x1601_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x05,
        .applicationObject1 = 0x21110020,
        .applicationObject2 = 0x21120108,
        .applicationObject3 = 0x21120208,
        .applicationObject4 = 0x21120308,
        .applicationObject5 = 0x21120408
    },
    .x1602_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x21200110,
        .applicationObject2 = 0x21200210,
        .applicationObject3 = 0x21200310
    },
    .x1603_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x21210120,
        .applicationObject2 = 0x21210220
    },
    .x1604_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x21300120,
        .applicationObject2 = 0x21300220
    },
    .x1605_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x21310120,
        .applicationObject2 = 0x21310220
    },
    .x1606_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x21320108,
        .applicationObject2 = 0x21320208
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000210,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0064,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000220,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0064,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x05,
        .applicationObject1 = 0x22100108,
        .applicationObject2 = 0x22100208,
        .applicationObject3 = 0x22100308,
        .applicationObject4 = 0x22100408,
        .applicationObject5 = 0x22100510
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x22200110,
        .applicationObject2 = 0x22200210,
        .applicationObject3 = 0x22200308
    }
};

canboss_master_ATTR_RAM canboss_master_RAM_t canboss_master_RAM = {
    .x1001_errorRegister = 0x00,
    .x1008_manufacturerDeviceName = {'C', 'A', 'N', 'b', 'o', 's', 's', '-', 'M', 'a', 's', 't', 'e', 'r', 0},
    .x1009_manufacturerHardwareVersion = {'1', '.', '0', 0},
    .x100A_manufacturerSoftwareVersion = {'1', '.', '0', 0},
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x2110_IO_AnalogeEingaenge_sub0 = 0x04,
    .x2110_IO_AnalogeEingaenge = {0, 0, 0, 0},
    .x2111_IO_Temperatur = 0.0,
    .x2112_IO_DigitaleEingaenge_sub0 = 0x04,
    .x2112_IO_DigitaleEingaenge = {false, false, false, false},
    .x2120_antriebStatus = {
        .highestSub_indexSupported = 0x03,
        .statusword = 0x0000,
        .drehzahlRampe = 0,
        .drehzahlIst = 0
    },
    .x2121_antriebMesswerte = {
        .highestSub_indexSupported = 0x02,
        .motorstromMA = 0,
        .temperaturEndstufe = 0.0
    },
    .x2130_sensorKlima = {
        .highestSub_indexSupported = 0x02,
        .temperatur = 0.0,
        .relativeFeuchte = 0.0
    },
    .x2131_sensorUmgebung = {
        .highestSub_indexSupported = 0x02,
        .luftdruckHPa = 0.0,
        .messzaehler = 0x00000000
    },
    .x2132_sensorAlarm = {
        .highestSub_indexSupported = 0x02,
        .alarmstatus = 0x00,
        .alarmAktiv = false
    },
    .x2210_IO_Kommando = {
        .highestSub_indexSupported = 0x05,
        .ausgang1 = false,
        .ausgang2 = false,
        .ausgang3 = false,
        .ausgang4 = false,
        .sollwert = 0
    },
    .x2220_antriebKommando = {
        .highestSub_indexSupported = 0x03,
        .controlword = 0x0000,
        .drehzahlSollwert = 0,
        .bremseAktiv = false
    }
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1404_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1405_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1406_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[5];
    OD_obj_record_t o_1601_RPDOMappingParameter[6];
    OD_obj_record_t o_1602_RPDOMappingParameter[4];
    OD_obj_record_t o_1603_RPDOMappingParameter[3];
    OD_obj_record_t o_1604_RPDOMappingParameter[3];
    OD_obj_record_t o_1605_RPDOMappingParameter[3];
    OD_obj_record_t o_1606_RPDOMappingParameter[3];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[6];
    OD_obj_record_t o_1A01_TPDOMappingParameter[4];
    OD_obj_array_t o_2110_IO_AnalogeEingaenge;
    OD_obj_var_t o_2111_IO_Temperatur;
    OD_obj_array_t o_2112_IO_DigitaleEingaenge;
    OD_obj_record_t o_2120_antriebStatus[4];
    OD_obj_record_t o_2121_antriebMesswerte[3];
    OD_obj_record_t o_2130_sensorKlima[3];
    OD_obj_record_t o_2131_sensorUmgebung[3];
    OD_obj_record_t o_2132_sensorAlarm[3];
    OD_obj_record_t o_2210_IO_Kommando[6];
    OD_obj_record_t o_2220_antriebKommando[4];
} canboss_masterObjs_t;

static CO_PROGMEM canboss_masterObjs_t canboss_masterObjs = {
    .o_1000_deviceType = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &canboss_master_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &canboss_master_RAM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 14
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &canboss_master_RAM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 3
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &canboss_master_RAM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 3
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &canboss_master_RAM.x1010_storeParameters_sub0,
        .dataOrig = &canboss_master_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &canboss_master_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &canboss_master_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &canboss_master_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &canboss_master_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &canboss_master_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &canboss_master_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1404_RPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1404_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1404_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1404_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1404_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1405_RPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1405_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1405_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1405_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1405_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1406_RPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1406_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1406_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1406_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1406_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1604_RPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1604_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1605_RPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1605_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1606_RPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1606_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2110_IO_AnalogeEingaenge = {
        .dataOrig0 = &canboss_master_RAM.x2110_IO_AnalogeEingaenge_sub0,
        .dataOrig = &canboss_master_RAM.x2110_IO_AnalogeEingaenge[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2111_IO_Temperatur = {
        .dataOrig = &canboss_master_RAM.x2111_IO_Temperatur,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2112_IO_DigitaleEingaenge = {
        .dataOrig0 = &canboss_master_RAM.x2112_IO_DigitaleEingaenge_sub0,
        .dataOrig = &canboss_master_RAM.x2112_IO_DigitaleEingaenge[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_2120_antriebStatus = {
        {
            .dataOrig = &canboss_master_RAM.x2120_antriebStatus.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2120_antriebStatus.statusword,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &canboss_master_RAM.x2120_antriebStatus.drehzahlRampe,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &canboss_master_RAM.x2120_antriebStatus.drehzahlIst,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2121_antriebMesswerte = {
        {
            .dataOrig = &canboss_master_RAM.x2121_antriebMesswerte.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2121_antriebMesswerte.motorstromMA,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_RAM.x2121_antriebMesswerte.temperaturEndstufe,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2130_sensorKlima = {
        {
            .dataOrig = &canboss_master_RAM.x2130_sensorKlima.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2130_sensorKlima.temperatur,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_RAM.x2130_sensorKlima.relativeFeuchte,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2131_sensorUmgebung = {
        {
            .dataOrig = &canboss_master_RAM.x2131_sensorUmgebung.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2131_sensorUmgebung.luftdruckHPa,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &canboss_master_RAM.x2131_sensorUmgebung.messzaehler,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2132_sensorAlarm = {
        {
            .dataOrig = &canboss_master_RAM.x2132_sensorAlarm.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2132_sensorAlarm.alarmstatus,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2132_sensorAlarm.alarmAktiv,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        }
    },
    .o_2210_IO_Kommando = {
        {
            .dataOrig = &canboss_master_RAM.x2210_IO_Kommando.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2210_IO_Kommando.ausgang1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2210_IO_Kommando.ausgang2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2210_IO_Kommando.ausgang3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_TPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2210_IO_Kommando.ausgang4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_TPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2210_IO_Kommando.sollwert,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2220_antriebKommando = {
        {
            .dataOrig = &canboss_master_RAM.x2220_antriebKommando.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &canboss_master_RAM.x2220_antriebKommando.controlword,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &canboss_master_RAM.x2220_antriebKommando.drehzahlSollwert,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &canboss_master_RAM.x2220_antriebKommando.bremseAktiv,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_TPDO,
            .dataLength = 1
        }
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static canboss_master_ATTR_OD OD_entry_t canboss_masterList[] = {
    {0x1000, 0x01, ODT_VAR, &canboss_masterObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &canboss_masterObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &canboss_masterObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &canboss_masterObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &canboss_masterObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &canboss_masterObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &canboss_masterObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &canboss_masterObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &canboss_masterObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1010, 0x05, ODT_ARR, &canboss_masterObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &canboss_masterObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &canboss_masterObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &canboss_masterObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &canboss_masterObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &canboss_masterObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &canboss_masterObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &canboss_masterObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &canboss_masterObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &canboss_masterObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &canboss_masterObjs.o_1280_SDOClientParameter, NULL},
    {0x1400, 0x04, ODT_REC, &canboss_masterObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &canboss_masterObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &canboss_masterObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &canboss_masterObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1404, 0x04, ODT_REC, &canboss_masterObjs.o_1404_RPDOCommunicationParameter, NULL},
    {0x1405, 0x04, ODT_REC, &canboss_masterObjs.o_1405_RPDOCommunicationParameter, NULL},
    {0x1406, 0x04, ODT_REC, &canboss_masterObjs.o_1406_RPDOCommunicationParameter, NULL},
    {0x1600, 0x05, ODT_REC, &canboss_masterObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x06, ODT_REC, &canboss_masterObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x04, ODT_REC, &canboss_masterObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x03, ODT_REC, &canboss_masterObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1604, 0x03, ODT_REC, &canboss_masterObjs.o_1604_RPDOMappingParameter, NULL},
    {0x1605, 0x03, ODT_REC, &canboss_masterObjs.o_1605_RPDOMappingParameter, NULL},
    {0x1606, 0x03, ODT_REC, &canboss_masterObjs.o_1606_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &canboss_masterObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &canboss_masterObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x06, ODT_REC, &canboss_masterObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x04, ODT_REC, &canboss_masterObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x2110, 0x05, ODT_ARR, &canboss_masterObjs.o_2110_IO_AnalogeEingaenge, NULL},
    {0x2111, 0x01, ODT_VAR, &canboss_masterObjs.o_2111_IO_Temperatur, NULL},
    {0x2112, 0x05, ODT_ARR, &canboss_masterObjs.o_2112_IO_DigitaleEingaenge, NULL},
    {0x2120, 0x04, ODT_REC, &canboss_masterObjs.o_2120_antriebStatus, NULL},
    {0x2121, 0x03, ODT_REC, &canboss_masterObjs.o_2121_antriebMesswerte, NULL},
    {0x2130, 0x03, ODT_REC, &canboss_masterObjs.o_2130_sensorKlima, NULL},
    {0x2131, 0x03, ODT_REC, &canboss_masterObjs.o_2131_sensorUmgebung, NULL},
    {0x2132, 0x03, ODT_REC, &canboss_masterObjs.o_2132_sensorAlarm, NULL},
    {0x2210, 0x06, ODT_REC, &canboss_masterObjs.o_2210_IO_Kommando, NULL},
    {0x2220, 0x04, ODT_REC, &canboss_masterObjs.o_2220_antriebKommando, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _canboss_master = {
    (sizeof(canboss_masterList) / sizeof(canboss_masterList[0])) - 1,
    &canboss_masterList[0]
};

OD_t *canboss_master = &_canboss_master;
